language: java
jdk:
- oraclejdk7
script:
- "./gradlew clean test dist"
deploy:
  provider: releases
  api_key:
    secure: D9LX+bDj7QyFRSzfUGpYf55cGEHn6zIWVi6N0hjDZQeCZGreE8XY6uewVy4lI+RdE1VOkBMdj/J/mJInF6yDBQm+uwn9BMsk/O2YoCalIb9rcTptkrw+OMZiuI82FXqp8fbMjdazKitB4TZzvBsnd58KmVxhBen9ldNcszRNa1Y=
  file: "shr/build/libs/shr.war"
  on:
    tags: false
    all_branches: true
  skip_cleanup: true

before_deploy: git fetch --tags